### PR TITLE
feat: Add anchors to sections for day one

### PR DESCRIPTION
**Pull request by amerikan**
- adds linkable anchors to sections so that we can easily link to specific sections within a page (in this case I just had time to do it for day 1, but would be good if all Days had them)
- sets up css variables for easy re-use of main theme color

### CODE REVIEW

**Comment by amerikan** [comment]
@rockygg @ayojackay can you take a look at this. And maybe consider doing this for all the days, would be useful when I have to share links with students, but want them to go to specific section on the page.

**Comment by ayojackay** [comment]
@amerikan I think this is a great idea. I can see it being helpful for sure! @rockygg , what do you think? 👀

**Comment by amerikan** [comment]
> @amerikan I think this is a great idea. I can see it being helpful for sure! @rockygg , what do you think? 👀

Will make it easy for me to send links to students. Right now I have to say go to X link then scroll down to Y section 😬

**Review by rockygg — APPROVED** [review]
Great idea!

**Comment by ayojackay** [comment]
@amerikan It's been approved so I'll merge it in and will update all days soon to reflect the same. Thank you for your suggestions and contribution!!!!

**Pull request merged**
