### PR TITLE
fix: display order lists for daily/take home challenges

### PR DESCRIPTION
**Pull request by amerikan**
- it's beneficial to see the lists for daily and take home challenge as numbered steps, this uses ol's for them and ensures they appear

### CODE REVIEW

**Comment by amerikan** [comment]
@rockygg @ayojackay please consider this 🙏🏼

**Comment by ayojackay** [comment]
Hey @amerikan ! I think this is great. I went ahead and tagged @rockygg to review!

**Review by rockygg — APPROVED** [review]
I agree, I hope this encourages them to not skip around the instructions!

**Comment by amerikan** [comment]
@ayojackay @rockygg awesome, excited to see this deployed lol

**Pull request merged**
